---

weapons:
  - id: sword
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 0.65
      soldier: 0.55
      villager: 0.55
      spearman: 0.40
      dog: 0.45
      wagon: 0.35
      knight: 0.15
      trebuchet: 0.3
      merman: 0.55
      mage: 0.55
      structure: 0.35
      commander: 0.10
      ballista: 0.35
      giant: 0.05
      rifleman: 0.65
      thief: 0.95

...
